name: Java CI with Maven

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: openjdk:22-ea-jdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Java version
        run: java -version

      - name: Make mvnw executable
        if: hashFiles('mvnw') != ''
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: target/*.jar

            # ---- НОВАЯ ЗАДАЧА: SAST с Semgrep ----
            sast:
              runs-on: ubuntu-latest
              needs: build          # опционально: ждём завершения сборки
              steps:
                - name: Checkout code
                  uses: actions/checkout@v4

                - name: Run Semgrep
                  uses: semgrep/semgrep-action@v1
                  with:
                    config: auto
                    output: semgrep.sarif
                    output_format: sarif

                - name: Upload SARIF report
                  uses: github/codeql-action/upload-sarif@v3
                  with:
                    sarif_file: semgrep.sarif
                    category: semgrep

