name: Semgrep SAST Scan

# Триггеры для запуска: по pull request, push в основную ветку и по расписанию (крон)
on:
  pull_request:
  push:
    branches: ["main", "master"]
  schedule:
    - cron: '20 17 * * *' # Запуск каждый день в 17:20 UTC
  workflow_dispatch: # Для ручного запуска из интерфейса GitHub

# Важно: определение необходимых прав доступа
permissions:
  # Обязательное право для загрузки SARIF-файлов в GitHub Advanced Security
  security-events: write
  # Эти права нужны, если репозиторий приватный или внутренний
  contents: read
  actions: read

jobs:
  semgrep-sast-job:
    name: Semgrep SAST Scan
    # Запускаем джобу в официальном Docker-образе Semgrep, чтобы не возиться с его установкой
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      # 1. Клонируем код репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Запускаем Semgrep: сканируем код и сохраняем результаты в SARIF-формате
      - name: Run Semgrep CI
        run: semgrep ci --sarif > semgrep.sarif
        # Переменная окружения для доступа к правилам Semgrep Cloud
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      # 3. Загружаем SARIF-файл в GitHub Advanced Security Dashboard
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Указываем путь к файлу, который мы создали на предыдущем шаге
          sarif_file: semgrep.sarif
        # `always()` гарантирует, что отчёт будет загружен даже при ошибках в scan-шаге.
        if: ${{ always() }}